### ISSUE TITLE
CMDB IC Searchs stop to work after installed ITSM-CIAttributeCollection v 6.0.2

### ISSUE THREAD

**Issue by richieri** [reneeb/otrs-ITSM-CIAttributeCollection#3]
Hi,

I'm not sure if this issue affects all OTRS versions. I'm using OTRS and ITSM 6.0.26.

Step-by-step:

1. Click on CMDB -> Search
2. Select a class

On a system WITHOUT the Addon, we get this:
![Seleção_909](https://user-images.githubusercontent.com/2002125/90266103-e679f880-de29-11ea-9533-5d2372427c83.png)

On a system WITH the AddOn, we get this:
![image](https://user-images.githubusercontent.com/2002125/90264636-c3e6e000-de27-11ea-8f5c-e9c2f74864f6.png)

I think it's releated to ITSM.Agent.ConfigItem.Search.CIAttrColl.js

**Comment by reneeb** [comment]
Thanks for the report. I'll have a look at it next week.

**Comment by reneeb** [comment]
Fixed in latest version...

**Comment by richieri** [comment]
Thanks!
